api/urls.py
from django.conf.urls import url
from api import views

urlpatterns = [
    # 書籍
    url(r'^v1/books/$', views.book_list, name='book_list'),     # 一覧
]

cms/urls.py
from django.conf.urls import url
from cms import views


urlpatterns = [
    # 書籍
    url(r'^home/$', views.home, name='home'),
    url(r'^book/$', views.book_list, name='book_list'),   # 一覧
    url(r'^book/add/$', views.book_edit, name='book_add'),  # 登録
    url(r'^book/mod/(?P<book_id>\d+)/$', views.book_edit, name='book_mod'),  # 修正
    url(r'^book/del/(?P<book_id>\d+)/$', views.book_del, name='book_del'),   # 削除

    url(r'^python/$', views.python_book_list, name='python_book_list'),   # 一覧
    url(r'^python/add/$', views.python_book_edit, name='python_book_add'),  # 登録
    url(r'^python/mod/(?P<python_book_id>\d+)/$', views.python_book_edit, name='python_book_mod'),  # 修正
    url(r'^python/del/(?P<python_book_id>\d+)/$', views.python_book_del, name='python_book_del'),   # 削除

    # 感想
    url(r'^impression/(?P<book_id>\d+)/$', views.ImpressionList.as_view(), name='impression_list'),  # 一覧
    url(r'^impression/add/(?P<book_id>\d+)/$', views.impression_edit, name='impression_add'),  # 登録
    url(r'^impression/mod/(?P<book_id>\d+)/(?P<impression_id>\d+)/$', views.impression_edit, name='impression_mod'),  # 修正
    url(r'^impression/del/(?P<book_id>\d+)/(?P<impression_id>\d+)/$', views.impression_del, name='impression_del'),   # 削除

    url(r'^python_impression/(?P<python_book_id>\d+)/$', views.python_ImpressionList.as_view(), name='python_impression_list'),  # 一覧
    url(r'^python_impression/add/(?P<python_book_id>\d+)/$', views.python_impression_edit, name='python_impression_add'),  # 登録
    url(r'^python_impression/mod/(?P<python_book_id>\d+)/(?P<python_impression_id>\d+)/$', views.python_impression_edit, name='python_impression_mod'),  # 修正
    url(r'^python_impression/del/(?P<python_book_id>\d+)/(?P<python_impression_id>\d+)/$', views.python_impression_del, name='python_impression_del'),   # 削除
]

mybook/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include   # ←, includeを追加
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cms/', include('cms.urls', namespace='cms')),
    url(r'^api/', include('api.urls', namespace='api')),  # ここを追加
]

cms/models.py
from django.db import models
from django.http import HttpResponse
from django.contrib.auth.models import User
# Create your models here.


class Book(models.Model):
    """書籍"""
    func_name = models.CharField('関数名', max_length=255)
    program_name = models.CharField('プログラム名', max_length=255)
    tag = models.CharField('タグ名', max_length=255, blank=True)
    author = models.CharField('著者名', max_length=255, blank=True)
    Github = models.CharField('Github', max_length=255, blank=True)

class python_Book(models.Model):
    """書籍"""
    func_name = models.CharField('関数名', max_length=255)
    program_name = models.CharField('プログラム名', max_length=255)
    tag = models.CharField('タグ名', max_length=255, blank=True)
    author = models.CharField('著者名', max_length=255, blank=True)
    Github = models.CharField('Github', max_length=255, blank=True)

class Impression(models.Model):
    """感想"""
    book = models.ForeignKey(Book, verbose_name='関数名', related_name='impressions')
    comment = models.TextField('コメント', blank=True)

class python_Impression(models.Model):
    """感想"""
    book = models.ForeignKey(python_Book, verbose_name='関数名', related_name='impressions')
    comment = models.TextField('コメント', blank=True)

cms/forms.py
from django.forms import ModelForm
from django import forms
from cms.models import Book,Impression

class BookForm(ModelForm):
    """書籍のフォーム"""
    class Meta:
        model = Book
        fields = ('func_name', 'program_name', 'tag','author','Github',)

class ImpressionForm(ModelForm):
    """感想のフォーム"""
    class Meta:
        model = Impression
        fields = ('comment', )

cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from cms.models import Book, Impression , python_Book , python_Impression
from cms.forms import BookForm, ImpressionForm
from django.db.models import Q


def home(request):
    """書籍の一覧"""
    if request.GET.get('your_name'):
        d = {'your_name': request.GET.get('your_name')}
        books = Book.objects.filter(Q(func_name__contains=request.GET.get('your_name'))| Q(program_name__contains=request.GET.get('your_name'))|Q(tag__contains=request.GET.get('your_name'))|Q(author__contains=request.GET.get('your_name')))
    else:
        books = Book.objects.all().order_by('id')
    return render(request, 'cms/home.html', {'books': books})

def book_list(request):
    """書籍の一覧"""
    if request.GET.get('your_name'):
        d = {'your_name': request.GET.get('your_name')}
        books = Book.objects.filter(Q(func_name__icontains=request.GET.get('your_name'))| Q(program_name__icontains=request.GET.get('your_name'))|Q(tag__icontains=request.GET.get('your_name'))|Q(author__icontains=request.GET.get('your_name')))
    else:
        books = Book.objects.all().order_by('id')
    return render(request, 'cms/book_list.html', {'books': books})

def book_edit(request, book_id=None):
    """書籍の編集"""
    if book_id:  # book_id が指定されている (修正時)
        book = get_object_or_404(Book, pk=book_id)
    else:  # book_id が指定されていない (追加時)
        book = Book()

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)  # POST された request データからフォームを作成
        if form.is_valid():  # フォームのバリデーション
            book = form.save(commit=False)
            book.save()
            return redirect('cms:book_list')
    else:  # GET の時
        form = BookForm(instance=book)  # book インスタンスからフォームを作成

    return render(request, 'cms/book_edit.html', dict(form=form, book_id=book_id))

def book_del(request, book_id):
    """書籍の削除"""
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return redirect('cms:book_list')

class ImpressionList(ListView):
    """感想の一覧"""
    context_object_name='impressions'
    template_name='cms/impression_list.html'
    paginate_by = 2  # １ページは最大2件ずつでページングする

    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book, pk=kwargs['book_id'])  # 親の書籍を読む
        impressions = book.impressions.all().order_by('id')   # 書籍の子供の、感想を読む
        self.object_list = impressions

        context = self.get_context_data(object_list=self.object_list, book=book)
        return self.render_to_response(context)

def impression_del(request, book_id, impression_id):
    """感想の削除"""
    impression = get_object_or_404(Impression, pk=impression_id)
    impression.delete()
    return redirect('cms:impression_list', book_id=book_id)

def impression_edit(request, book_id, impression_id=None):
    """感想の編集"""
    book = get_object_or_404(Book, pk=book_id)  # 親の書籍を読む
    if impression_id:   # impression_id が指定されている (修正時)
        impression = get_object_or_404(Impression, pk=impression_id)
    else:               # impression_id が指定されていない (追加時)
        impression = Impression()

    if request.method == 'POST':
        form = ImpressionForm(request.POST, instance=impression)  # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            impression = form.save(commit=False)
            impression.book = book  # この感想の、親の書籍をセット
            impression.save()
            return redirect('cms:impression_list', book_id=book_id)
    else:    # GET の時
        form = ImpressionForm(instance=impression)  # impression インスタンスからフォームを作成

    return render(request,
                  'cms/impression_edit.html',
                  dict(form=form, book_id=book_id, impression_id=impression_id))


def python_book_list(request):
    """書籍の一覧"""
    if request.GET.get('your_name'):
        d = {'your_name': request.GET.get('your_name')}
        python_books = python_Book.objects.filter(Q(func_name__icontains=request.GET.get('your_name'))| Q(program_name__icontains=request.GET.get('your_name'))|Q(tag__icontains=request.GET.get('your_name'))|Q(author__icontains=request.GET.get('your_name')))
    else:
        python_books = python_Book.objects.all().order_by('id')
    return render(request, 'cms/python_list.html', {'python_books': python_books})

def python_book_edit(request, python_book_id=None):
    """書籍の編集"""
    if python_book_id:  # book_id が指定されている (修正時)
        python_book = get_object_or_404(python_Book, pk=python_book_id)
    else:  # book_id が指定されていない (追加時)
        python_book = python_Book()

    if request.method == 'POST':
        form = BookForm(request.POST, instance=python_book)  # POST された request データからフォームを作成
        if form.is_valid():  # フォームのバリデーション
            python_book = form.save(commit=False)
            python_book.save()
            return redirect('cms:python_book_list')
    else:  # GET の時
        form = BookForm(instance=python_book)  # book インスタンスからフォームを作成

    return render(request, 'cms/python_book_edit.html', dict(form=form, python_book_id=python_book_id))

def python_book_del(request, python_book_id):
    """書籍の削除"""
    python_book = get_object_or_404(python_Book, pk=python_book_id)
    python_book.delete()
    return redirect('cms:python_book_list')

class python_ImpressionList(ListView):
    """感想の一覧"""
    context_object_name='python_impressions'
    template_name='cms/python_impression_list.html'
    paginate_by = 2  # １ページは最大2件ずつでページングする

    def get(self, request, *args, **kwargs):
        python_book = get_object_or_404(python_Book, pk=kwargs['python_book_id'])  # 親の書籍を読む
        python_impressions = python_book.impressions.all().order_by('id')   # 書籍の子供の、感想を読む
        self.object_list = python_impressions

        context = self.get_context_data(object_list=self.object_list, python_book=python_book)
        return self.render_to_response(context)

def python_impression_edit(request, python_book_id, python_impression_id=None):
    """感想の編集"""
    python_book = get_object_or_404(python_Book, pk=python_book_id)  # 親の書籍を読む
    if python_impression_id:   # impression_id が指定されている (修正時)
        python_impression = get_object_or_404(python_Impression, pk=python_impression_id)
    else:               # impression_id が指定されていない (追加時)
        python_impression = python_Impression()

    if request.method == 'POST':
        form = ImpressionForm(request.POST, instance=python_impression)  # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            python_impression = form.save(commit=False)
            python_impression.book = python_book  # この感想の、親の書籍をセット
            python_impression.save()
            return redirect('cms:python_impression_list', python_book_id=python_book_id)
    else:    # GET の時
        form = ImpressionForm(instance=python_impression)  # impression インスタンスからフォームを作成

    return render(request,
                  'cms/python_impression_edit.html',
                  dict(form=form, python_book_id=python_book_id, python_impression_id=python_impression_id))

def python_impression_del(request, python_book_id, python_impression_id):
    """感想の削除"""
    python_impression = get_object_or_404(python_Impression, pk=python_impression_id)
    python_impression.delete()
    return redirect('cms:python_impression_list', python_book_id=python_book_id)

cms/templates/cms/book_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}関数の編集{% endblock title %}

{% block content %}
    <h3 class="page-header">関数の編集</h3>
    {% if book_id %}
    <form action="{% url 'cms:book_mod' book_id=book_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:book_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-info">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:book_list' %}" class="btn btn-warning btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/book_list.html
{% extends "base.html" %}

{% block title %}関数名一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">関数名一覧</h3>
    <h3>検索</h3>
    <form action="" method="GET">
        <label><input type="text" size="20" name="your_name"></label>
        {{ form.q }}
        <input type="submit" value="検索">
    </form>
    <br>
    <a href="{% url 'cms:home' %}" class="btn btn-warning btn-sm">戻る</a>
    <a href="{% url 'cms:book_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th><Div Align="center">関数名</Div></th>
          <th><Div Align="center">プログラム名</Div></th>
          <th><Div Align="center">タグ名</Div></th>
          <th><Div Align="center">作成者</Div></th>
            <th><Div Align="center">Github</Div></th>
          <th><Div Align="center">操作</Div></th>      </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <td><Div Align="center">{{ book.func_name }}</Div></td>
          <td><Div Align="center">{{ book.program_name }}</Div></td>
          <td><Div Align="center">{{ book.tag }}</Div></td>
          <td><Div Align="center">{{ book.author }}</Div></td>
            <td><Div Align="center"><a href="{{ book.Github }}" class="btn btn-success btn-sm">Github</a></Div></td>
          <td><Div Align="center">
              <a href="{% url 'cms:book_mod' book_id=book.id %}" class="btn btn-warning btn-sm">修正</a>
              <button class="btn btn-danger btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ book.id }}" url="{% url 'cms:book_del' book_id=book.id %}">削除</button>
              <a href="{% url 'cms:impression_list' book_id=book.id %}" class="btn btn-info btn-sm ">プログラムソース</a>
          </Div></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
      {% endif %}
      {% for linkpage in page_obj.paginator.page_range %}
        {% ifequal linkpage page_obj.number %}
          <li  class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
          <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">プログラムの削除</h4>
      </div>
      <div class="modal-body">
        <p>本当に削除しますか?</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

cms/templates/cms/impression_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}プログラムの編集{% endblock title %}

{% block content %}
    <h3 class="page-header">プログラムの編集</h3>
    {% if impression_id %}
    <form action="{% url 'cms:impression_mod' book_id=book_id impression_id=impression_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:impression_add' book_id=book_id %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:impression_list' book_id=book_id %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/impression_list.html
{% extends "base.html" %}

{% block title %}プログラムのソース{% endblock title %}

{% block extrahead %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).attr("pk"));
     $('#del_url').attr('href', $(this).attr("url"));
  });
});
</script>
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">プログラムの一覧 <small>{{ book.func_name }}</small></h3>
    <a href="{% url 'cms:impression_add' book_id=book.id %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
            <td>ソース</td>
            <td>操作</td>
        </tr>
      </thead>
      <tbody>
        {% for impression in impressions %}
        <tr>
          <td>{{ impression.comment|linebreaksbr }}</td>
          <td>
            <a href="{% url 'cms:impression_mod' book_id=book.id impression_id=impression.id %}" class="btn btn-default btn-sm">修正</a>
            <button class="btn btn-default btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ impression.id }}" url="{% url 'cms:impression_del' book_id=book.id impression_id=impression.id %}">削除</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
      {% endif %}
      {% for linkpage in page_obj.paginator.page_range %}
        {% ifequal linkpage page_obj.number %}
          <li  class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
          <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}

    <div>
      <a href="{% url 'cms:book_list' %}" class="btn btn-default btn-sm">戻る</a>
    </div>

{# 削除を確認するモーダル ダイアログ #}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">プログラムの削除</h4>
      </div>
      <div class="modal-body">
        <p>本当にID: <span id= "del_pk"></span> 削除しますか?</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

cms/templates/cms/python_book_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}python関数の編集{% endblock title %}

{% block content %}
    <h3 class="page-header">python関数の編集</h3>
    {% if python_book_id %}
    <form action="{% url 'cms:python_book_mod' python_book_id=python_book_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:python_book_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-info">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:python_book_list' %}" class="btn btn-warning btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/python_impression_list.html
{% extends "base.html" %}

{% block title %}プログラムのソース{% endblock title %}

{% block extrahead %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).attr("pk"));
     $('#del_url').attr('href', $(this).attr("url"));
  });
});
</script>
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">プログラムの一覧 <small>{{ python_book.func_name }}</small></h3>
    <a href="{% url 'cms:python_impression_add' python_book_id=python_book.id %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
            <td>ソース</td>
            <td>操作</td>
        </tr>
      </thead>
      <tbody>
        {% for python_impression in python_impressions %}
        <tr>
          <td>{{ python_impression.comment|linebreaksbr }}</td>
          <td>
            <a href="{% url 'cms:python_impression_mod' python_book_id=python_book.id python_impression_id=python_impression.id %}" class="btn btn-default btn-sm">修正</a>
            <button class="btn btn-default btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ python_impression.id }}" url="{% url 'cms:python_impression_del' python_book_id=python_book.id python_impression_id=python_impression.id %}">削除</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
      {% endif %}
      {% for linkpage in page_obj.paginator.page_range %}
        {% ifequal linkpage page_obj.number %}
          <li  class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
          <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}

    <div>
      <a href="{% url 'cms:python_book_list' %}" class="btn btn-default btn-sm">戻る</a>
    </div>

{# 削除を確認するモーダル ダイアログ #}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">プログラムの削除</h4>
      </div>
      <div class="modal-body">
        <p>本当にID: <span id= "del_pk"></span> 削除しますか?</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

cms/templates/cms/python_list.html
{% extends "base.html" %}

{% block title %}関数名一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">python関数名一覧</h3>
    <h3>検索</h3>
    <form action="" method="GET">
        <label><input type="text" size="20" name="your_name"></label>
        {{ form.q }}
        <input type="submit" value="検索">
    </form>
    <br>
    <a href="{% url 'cms:home' %}" class="btn btn-warning btn-sm">戻る</a>
    <a href="{% url 'cms:python_book_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th><Div Align="center">関数名</Div></th>
          <th><Div Align="center">プログラム名</Div></th>
          <th><Div Align="center">タグ名</Div></th>
          <th><Div Align="center">作成者</Div></th>
            <th><Div Align="center">Github</Div></th>
          <th><Div Align="center">操作</Div></th>      </tr>
      </thead>
      <tbody>
        {% for python_book in python_books %}
        <tr>
            <td><Div Align="center">{{ python_book.func_name }}</Div></td>
            <td><Div Align="center">{{ python_book.program_name }}</Div></td>
            <td><Div Align="center">{{ python_book.tag }}</Div></td>
            <td><Div Align="center">{{ python_book.author }}</Div></td>
            <td><Div Align="center"><a href="{{ python_book.Github }}" class="btn btn-success btn-sm">Github</a></Div></td>
            <td><Div Align="center">
                <a href="{% url 'cms:python_book_mod' python_book_id=python_book.id %}" class="btn btn-warning btn-sm">修正</a>
                <button class="btn btn-danger btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ python_book.id }}" url="{% url 'cms:python_book_del' python_book_id=python_book.id %}">削除</button>

              <a href="{% url 'cms:python_impression_list' python_book_id=python_book.id %}" class="btn btn-info btn-sm ">プログラムソース</a>
          </Div></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
      {% endif %}
      {% for linkpage in page_obj.paginator.page_range %}
        {% ifequal linkpage page_obj.number %}
          <li  class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
          <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">プログラムの削除</h4>
      </div>
      <div class="modal-body">
        <p>本当に削除しますか?</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}